name: GitHub Pages

on:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    branches:
      - main
      - master
    paths:
      - "content/**"
      - "static/**"
      - "templates/**"
      - "config.toml"
      - ".github/workflows/pages.yml"
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
    paths:
      - "content/**"
      - "static/**"
      - "templates/**"
      - "config.toml"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
          ZOLA_BUILD_DIR: public
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
